
name: Rebuild the frontend on the server of SWOB
on:
  push:
    branches:
    - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          cd /var/www/repos/smswithoutborders.com
          git checkout master
          git pull -r
          rm -rf build
          yarn install
          yarn build
          cp -r build/. /var/www/html/
